### ISSUE TITLE
ECONNRESET error shutting down a Node

### ISSUE THREAD

**Issue by albertosantini** [nkcmr/flic#1]
I have two processes: one with a Bridge and na anonymous Node, another one with an anonymous Node.

When I shutdown the process (Ctrl-C)  with standalone Node, the process with the Bridge displays the following error:
`{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }`

Adding `myBridge.on("error"...` or `myFirstNode.on("error"...` in the first process, that error is not catched.

However, I have `mySecondNode.on("error"...` and when I shutdown the process with the Bridge, the error callback is triggered.

Any hint?

**Comment by albertosantini** [comment]
DEBUG details about the process containing `bridge` and `master` node, when the second process is closed (containing another node):

```
...
flic:bridge Received SHOUT from master +0ms
  flic:node Node <-- Bridge: {"id":"1edaec89-78ae-4eec-972a-2abec5d5886f","method":"SHOUT","data":["argo.streaming","{\"heartbeat\":{\"time\":\"2015-05-17T13:35:22.818153Z\"}}"]} +2s
  flic:node Received SHOUT(argo.streaming) +0ms
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
  flic:bridge Node 'seed' has disconnected. Deleting... +578ms
  flic:bridge Node --> Bridge: {"id":"03049b1b-354a-4d5c-9a45-e0fb4f93815a","method":"SHOUT","data":["argo.streaming","{\"heartbeat\":{\"time\":\"2015-05-17T13:35:25.279052Z\"}}"],"nodeName":"master"} +1s
  flic:bridge Received SHOUT from master +0ms
  flic:node Node <-- Bridge: {"id":"a76fba99-bf2c-4586-8201-8d6276798330","method":"SHOUT","data":["argo.streaming","{\"heartbeat\":{\"time\":\"2015-05-17T13:35:25.279052Z\"}}"]} +2s
  flic:node Received SHOUT(argo.streaming) +0ms
  flic:bridge Node --> Bridge: {"id":"f00ecc88-5172-48af-8e2d-165c2b2875a6","method":"SHOUT","data":["argo.streaming","{\"heartbeat\":{\"time\":\"2015-05-17T13:35:27.818154Z\"}}"],"nodeName":"master"} +2s
  flic:bridge Received SHOUT from master +0ms
  flic:node Node <-- Bridge: {"id":"b09613e1-cefd-440c-b59b-0d23abbdb02a","method":"SHOUT","data":["argo.streaming","{\"heartbeat\":{\"time\":\"2015-05-17T13:35:27.818154Z\"}}"]} +2s
  flic:node Received SHOUT(argo.streaming) +0ms
...
```

The aim is catching that error.

**Comment by albertosantini** [comment]
How to reproduce it:

```
$ ./node_modules/.bin/flic --bridge  0.0.0.0:8221
[21:42:42][cli] initializing bridge
[21:42:42][cli] bridge is now listening on 0.0.0.0:8221
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:572:26)
```


`foo.js`
```
"use strict";

const flic = require("flic");

flic.createNode("node1", err => {
    if (err) {
        console.log(err);
    } else {
        console.log("node1 online!");
    }
});
```

```
$ node foo.js
node1 online!
```

Press Ctrl-C to stop `node1` and you see ECONNRESET exception in bridge terminal.

Basically it is missing socket error handler in the bridge.

**Comment by albertosantini** [comment]
Working on it.

Adding in the bridge

```
   socket.setEncoding('utf8')
   socket.setTimeout(0)
   socket.on('data', _.bind(this._handle_data, this, socket))
+  socket.on('error', _.bind(this._cleanup_dead_socket, this, socket))
```

Before the patch:
```
$ ./node_modules/.bin/flic --bridge  0.0.0.0:8221
[22:02:55][cli] initializing bridge
[22:02:55][cli] bridge is now listening on 0.0.0.0:8221
  flic:bridge new node (127.0.0.1:50879) +0ms
  flic:bridge node --> bridge: {"id":"357a1b76-b3d7-4388-8953-4599c1b49a04","method":"IDENT","data":[],"nodeName":"node2"} +0ms
  flic:bridge sending ACK (id: 357a1b76-b3d7-4388-8953-4599c1b49a04) +16ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:572:26)
```

After the patch (started and stopped the node twice):
```
$ ./node_modules/.bin/flic --bridge  0.0.0.0:8221
[21:57:55][cli] initializing bridge
[21:57:55][cli] bridge is now listening on 0.0.0.0:8221
  flic:bridge new node (127.0.0.1:50841) +0ms
  flic:bridge node --> bridge: {"id":"71951ecb-2799-45fe-a06d-553014ccf231","method":"IDENT","data":[],"nodeName":"node2"} +16ms
  flic:bridge sending ACK (id: 71951ecb-2799-45fe-a06d-553014ccf231) +0ms
  flic:bridge Node 'node2' has left. cleaning up... +5s
  flic:bridge new node (127.0.0.1:50843) +9s
  flic:bridge node --> bridge: {"id":"38e523e6-8fe0-425d-ad10-d52ed2467d81","method":"IDENT","data":[],"nodeName":"node2"} +15ms
  flic:bridge sending ACK (id: 38e523e6-8fe0-425d-ad10-d52ed2467d81) +0ms
  flic:bridge Node 'node2' has left. cleaning up... +7s
```

Preparing the PR
